<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class MahasiswaSeeder extends Seeder
{
    public function run()
    {
        DB::table('mahasiswa')->insert([
            // [
            //     'nim' => '2341760133',
            //     'nama' => 'Bagas Pratama',
            //     'email' => 'bagas@example.com',
            //     'no_hp' => '081234567890',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Raya Blimbing No. 99',
            //     'tmpt_lahir' => 'Malang',
            //     'password' => Hash::make('bagas123'),
            // ],
            // [
            //     'nim' => '2341760185',
            //     'nama' => 'Jessica Amelia',
            //     'email' => 'ameliajessica997@gmail.com',
            //     'no_hp' => '085731022917',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Kembang Turi No.20',
            //     'tmpt_lahir' => 'Blitar',
            //     'password' => Hash::make('jessi123'),
            // ],
            // [
            //     'nim' => '2341760066',
            //     'nama' => 'Nervalina Adzra Nora Aqilla',
            //     'email' => 'valinaadzraa@gmail.com',
            //     'no_hp' => '081357971553',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Soekarno Hatta Indah IV No. 21B',
            //     'tmpt_lahir' => 'Mojokerto',
            //     'password' => Hash::make('lino123'),
            // ],
            //[
            //    'nim' => '2341760127',
            //    'nama' => 'Veren Regina Tirsya',
            //    'email' => 'verenregina214@gmail.com',
            //    'no_hp' => '081249135132',
            //    'created_at' => now(),
            //    'updated_at' => now(),
            //    'alamat' => 'Jl. Kembang Turi No.02',
            //    'tmpt_lahir' => 'Tulungagung',
            //    'password' => Hash::make('verenregina214'),
            //],
            // [
            //     'nim' => '2341760111',
            //     'nama' => 'Aqela Calista',
            //     'email' => 'aqela.calista@example.com',
            //     'no_hp' => '08579135571',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Semanggi Barat No.15D',
            //     'tmpt_lahir' => 'Kediri',
            //     'password' => Hash::make('password111'),
            // ],
            // [
            //     'nim' => '2341760112',
            //     'nama' => 'Nichole Rossi',
            //     'email' => 'rosi@example.com',
            //     'no_hp' => '08579135572',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Semanggi Timur No.22A',
            //     'tmpt_lahir' => 'Malang',
            //     'password' => Hash::make('password112'),
            // ],
            // [
            //     'nim' => '2341760113',
            //     'nama' => 'Rizky Ahmad',
            //     'email' => 'rizky.ahmad@example.com',
            //     'no_hp' => '08579135573',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Mawar No.8B',
            //     'tmpt_lahir' => 'Surabaya',
            //     'password' => Hash::make('password113'),
            // ],
            // [
            //     'nim' => '2341760114',
            //     'nama' => 'Lia Putri',
            //     'email' => 'lia.putri@example.com',
            //     'no_hp' => '08579135574',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Melati No.10',
            //     'tmpt_lahir' => 'Jember',
            //     'password' => Hash::make('password114'),
            // ],
            // [
            //     'nim' => '2341760115',
            //     'nama' => 'Andi Saputra',
            //     'email' => 'andi.saputra@example.com',
            //     'no_hp' => '08579135575',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Kenanga No.5',
            //     'tmpt_lahir' => 'Banyuwangi',
            //     'password' => Hash::make('password115'),
            // ],
            // [
            //     'nim' => '2341760116',
            //     'nama' => 'Siti Rahma',
            //     'email' => 'siti.rahma@example.com',
            //     'no_hp' => '08579135576',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Anggrek No.3',
            //     'tmpt_lahir' => 'Blitar',
            //     'password' => Hash::make('password116'),
            // ],
            // [
            //     'nim' => '2341760117',
            //     'nama' => 'Dedi Kurniawan',
            //     'email' => 'dedi.kurniawan@example.com',
            //     'no_hp' => '08579135577',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Dahlia No.11',
            //     'tmpt_lahir' => 'Madiun',
            //     'password' => Hash::make('password117'),
            // ],
            // [
            //     'nim' => '2341760118',
            //     'nama' => 'Nina Kartika',
            //     'email' => 'nina.kartika@example.com',
            //     'no_hp' => '08579135578',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Flamboyan No.9',
            //     'tmpt_lahir' => 'Kediri',
            //     'password' => Hash::make('password118'),
            // ],
            // [
            //     'nim' => '2341760121',
            //     'nama' => 'Arya Mohan',
            //     'email' => 'arya.mohan@example.com',
            //     'no_hp' => '08579135579',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Cemara No.12',
            //     'tmpt_lahir' => 'Pasuruan',
            //     'password' => Hash::make('password121'),
            // ],
            // [
            //     'nim' => '2341760122',
            //     'nama' => 'Harry Vaughan',
            //     'email' => 'harry.vaughana@example.com',
            //     'no_hp' => '08579135580',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            //     'alamat' => 'Jl. Kamboja No.7',
            //     'tmpt_lahir' => 'Probolinggo',
            //     'password' => Hash::make('password122'),
            // ],
            [
                'nim' => '2341760123',
                'nama' => 'William Johnson',
                'email' => 'william.vaughana@example.com',
                'no_hp' => '08579135580',
                'created_at' => now(),
                'updated_at' => now(),
                'alamat' => 'Jl. Kamboja No.7',
                'tmpt_lahir' => 'Probolinggo',
                'password' => Hash::make('password123'),
            ],
        ]);
    }
}
